import type { Metadata } from "next";
import { Gabarito, Lexend } from "next/font/google";
import "./globals.css";

const gabarito = Gabarito({
  variable: "--font-gabarito",
  weight: ['400','700','900'],
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  weight: ['300','400','600'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.variable} ${lexend.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
